version: "3.9"

services:
  mysql:
    image: "mysql:8.0.11"
    environment:
        MYSQL_ROOT_PASSWORD_FILE: "/run/secrets/mysql/password"
    secrets:
      - source: mysql
        target: mysql/password
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "./mysql_data:/var/lib/mysql"
    configs:
      - source: userlist_init
        target: /docker-entrypoint-initdb.d/userlist.sql
    networks:
      - demonet
    ports:
        - "9906:3306"

  userlist:
    image: fendi74960/tp-info910:0.1.19
    build:             
      context: php
      dockerfile: Dockerfile
    secrets:
      - source: mysql
        target: mysql/password
    ports:
      - 9000:80
    networks:
      - demonet
    depends_on:
      - mysql

networks:
  demonet:

secrets:
  mysql:
    file: ./passwd

configs:
  userlist_init:
    file: ./init.mysql
