apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  labels: 
    app: userlistdemo
spec:
  resources:
    requests:
      storage: "1G"
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
