apiVersion: v1
kind: Service
metadata:
  name: userlist
  labels: 
    app: userlistdemo
    role: front
spec:
  type: ClusterIP
  selector:
    app: userlist
    role: front  
  ports:
  - port: 80
    targetPort: 80
    #nodePort: 32123
